// <auto-generated />
namespace Web_Crawler_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fir : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fir));
        
        string IMigrationMetadata.Id
        {
            get { return "202011220923343_fir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
